baseURL = "graphitedge.com.au"
languageCode = "en-us"
title = "Graphitedge"
themesDir = "../.."
theme = "hugo-hero-theme"

[params]
  google_analytics_id="UA-76054930-1"

  [params.homepage_meta_tags]
    meta_description = "Graphitedge is the public face for Helen Burgess. A Web Developer and trainer who works with SME Businesses."
    meta_og_title = "Graphitedge"
    meta_og_type = "website"
    meta_og_url = "https://"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Graphitedge is the public face for Helen Burgess. A Web Developer and trainer who works with SME Businesses"
    meta_twitter_card = "summary"
    meta_twitter_site = "@graphitedgeau"
    meta_twitter_creator = "@graphitedgeau"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"