baseurl = "https://graphitedge.com.au"
languageCode = "en-us"
title = "Graphitedge"
theme = "graphite-custom"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Graphitedge"
	description = "A Sharp Pencil & A Dream Can Take You Anywhere"

	email = "info@graphitedge.comm.au"
    phone = "+234 23 9873237"
    address = "234 Hidden Pond Road, Ashland City, TN 37015"
    year = 2018
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = ""

[params.sharethis]
    property = "5aa60cf5589d90001319f50e"
    custom = true

[params.google.analytics]
    trackerID = "UA-76054930-1"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/graphitedg"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/graphitedgeau"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = false
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = false
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fa-github"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:info@graphitedge.com.au"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
	