baseurl = "https://graphitedge.com.au"
languageCode = "en-us"
title = "Graphitedge"
theme = "hugo-creative"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Graphitedge"
	description = "A Sharp Pencil & A Dream Can Take You Anywhere"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "GraphitEdge"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
            blog      = "Blog"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "A Sharp Pencil & A Dream Can Take You Anywhere"
		subtitle   = "Keeping you & your business online through attention to detail with no bulldust just straight talking"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "Whether it is just keeping your site's content management system upto date or creating a new look and feel for your site or even making sure that it is as secure as it can be."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-cogs"
            title = "Website Master - The maintainer YOU need "
            description = "Since website downtime can be a costly thing for your business, Helen is able guide you through being a novice to web master in how to keep your site up and running. "

        [[params.services.list]]
			icon = "fa-object-group"
			title = "Responsive Design "
			description = "And if that sounds not like your ballpark then Helen is able to take your site mockups and using various techniques in CSS and HTML (with or without frameworks) to create and deploy a responsive website for you."

		[[params.services.list]]
            icon = "fa-shield-alt"
            title = "Security"
            description = "With Security being the topic of the moment, have Helen take a look at the security of your site via a Security Site Checkup. Helen can then advise you on how to keep your website and clients safe."



    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative with Graphitedge"

		[params.aside.button]
			text = ""
			link = ""

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "+61861025624"
		email = "info@graphitedge.com.au"

	# Google Maps section
	[params.location]
	latitude  = "-31.824685"
	longitude = "115.804274"
	maps_api_key = " AIzaSyCaUtRG0HJInM4Zlc401WO5RQJCoBiVYQg "
