baseurl = "https://graphitedge.com.au/"
googleAnalytics = ""
languageCode = "en-us"
theme = "graphite-custom"
title = "Graphitedge"
[[menu.main]]
name = "blog"
url = "/post/"
weight = 5
[[menu.main]]
name = "home"
url = "/"
weight = 1
[params]
address = "Greenwood Western Australia 6024"
background = ""
dateform = "January 2, 2006"
description = "A Sharp Pencil & A Dream Can Take You Anywhere"
email = "info@graphitedge.comm.au"
favicon = "/uploads/2018/03/19/graphiteLogoTrans.png"
footerenablecontact = true
footerenablefollowme = true
footerenableformwidget = true
footerenabletextwidget = false
name = "Graphitedge"
phone = "+618 6102 5624"
showclients = false
showdownload = false
showrecentworks = true
showservices = true
showsubheader = true
year = 2018
[params.disqus]
site = ""
[params.google.analytics]
trackerid = "UA-76054930-1"
[params.sharethis]
custom = true
property = "5aa60cf5589d90001319f50e"
[[params.social]]
footer = true
icon = "fa-facebook-square"
network = "facebook"
sharethis = true
title = "facebook"
url = "https://www.facebook.com/graphitedge"
[[params.social]]
footer = true
icon = "fa-twitter-square"
network = "twitter"
sharethis = true
title = "twitter"
url = "https://twitter.com/graphitedgeau"
[[params.social]]
footer = false
icon = "fa-instagram"
network = ""
sharethis = false
title = "instagram"
url = "https://www.instagram.com/nickname"
[[params.social]]
footer = false
icon = "fa-google-plus-square"
network = "googleplus"
sharethis = false
title = "google+"
url = "https://plus.google.com/+nickname"
[[params.social]]
footer = false
icon = "fa-linkedin-square"
network = "linkedin"
sharethis = false
title = "linkedin"
url = "https://www.linkedin.com/in/nickname"
[[params.social]]
footer = false
icon = "fa-tumblr-square"
network = "tumblr"
sharethis = false
title = "tumblr"
url = "https://nickname.tumblr.com"
[[params.social]]
footer = false
icon = "fa-github"
network = ""
sharethis = false
title = "github"
url = "https://github.com/nickname"
[[params.social]]
footer = false
icon = "fa-envelope"
network = "email"
sharethis = true
title = "email"
url = "mailto:info@graphitedge.com.au"
